server:
  port: 80
spring:
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: utf-8
  #datasource
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.9:3306/whh?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
  servlet:
    multipart:
      resolve-lazily: true
      max-request-size: 10MB
      max-file-size: 10MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
mybatis:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    local-cache-scope: statement
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: org.whh.bz.entity

redis:
    host: localhost
    port: 6379
#      database: 0
    connect-timeout: 5s
    # 读超时
    timeout: 5s
    # Lettuce 客户端的配置
    lettuce:
      pool:
        # 最小空闲连接
        min-idle: 0
        # 最大空闲连接
        max-idle: 8
        # 最大活跃连接
        max-active: 8
        # 从连接池获取连接 最大超时时间，小于等于0则表示不会超时
        max-wait: -1ms
logging:
  level:
    org:
      whh.bz.dao: debug
      springframework:
        boot:
          autoconfigure:
            logging: error
picUrl: "F:/log-1/src/main/resources/static/pics/"
maxCount: 9
