server:
  port: 80
spring:
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: utf-8
  #datasource
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.15:3306/whh?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      time
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
mybatis:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: org.whh.bz.entity
redis:
  host: localhost
  password:
  port: 6379
logging:
  level:
    org.whh.bz.dao: debug
tUrl: E:/ideaProject/log/src/main/resources/static/tempics/
lUrl: E:/ideaProject/log/src/main/resources/static/pics/

